library("plumber")
library("{{package_name}}")

#* @apiTitle {{package_name}}
#* @apiDescription RESTful API for {{package_name}} generated by the plumberizer package.
#* @apiVersion 0.0.1

{{functions_plumber}}
